server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      path: "/h2"
      enabled: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080
      client:
        registration:
          awuser-client:
            provider: auth
            client-id: awuser
            client-secret: 123456
            authorization-grant-type: client_credentials
            scope: users:read
        provider:
          auth:
            issuer-uri: http://localhost:8080
aw:
  user-api:
    url: 'http://localhost:8080'
    encoded-credentials: 'YWRtaW5AZW1haWwuY29tOmFkbWlu'