insert into USUARIO (ID, NAME, TIPO) VALUES (1, 'PEDRO1', 1);
insert into USUARIO (ID, NAME, TIPO) VALUES (2, 'PEDRO2', 1);
insert into USUARIO (ID, NAME, TIPO) VALUES (3, 'PEDRO3', 1);
insert into USUARIO (ID, NAME, TIPO) VALUES (4, 'PEDRO4', 1);
insert into FILME (IMDB_ID, NOTA, NUMERO_DE_NOTAS_DADAS, TITLE) VALUES ('tt1285016', 1, 3, 'A Rede Social');
insert into NOTA_FILME(ID, NOTA, FILME_ID, USUARIO_ID) VALUES (1, 1, 1, 1);
insert into NOTA_FILME(ID, NOTA, FILME_ID, USUARIO_ID) VALUES (2, 1, 1, 2);
insert into NOTA_FILME(ID, NOTA, FILME_ID, USUARIO_ID) VALUES (3, 1, 1, 3);